#!/usr/bin/env python3
import sys
from pathlib import Path

def main():
    if len(sys.argv) != 3:
        print("Usage: embed_png.py <input_png> <output_header>")
        return 2

    in_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    try:
        from PIL import Image
    except Exception as e:
        print("Error: Python Pillow (PIL) is required. Install python3-pil.")
        return 3

    if not in_path.exists():
        print(f"Input not found: {in_path}")
        return 4

    img = Image.open(in_path)
    img = img.convert('RGBA')
    w, h = img.size
    data = img.tobytes()  # RGBA bytes

    # Write header
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by tools/embed_png.py. Do not edit.\n')
        f.write('#pragma once\n')
        f.write('extern const unsigned int g_qr_w;\n')
        f.write('extern const unsigned int g_qr_h;\n')
        f.write('extern const unsigned char g_qr_rgba[];\n')
        f.write('\n')
        f.write('#ifdef RESOURCES_EMBED_IMPL\n')
        f.write('const unsigned int g_qr_w = %d;\n' % w)
        f.write('const unsigned int g_qr_h = %d;\n' % h)
        f.write('const unsigned char g_qr_rgba[] = {\n')

        # Emit as hex, 16 bytes per line
        line = []
        for i, b in enumerate(data):
            line.append(f'0x{b:02X}')
            if len(line) == 16:
                f.write('  ' + ', '.join(line) + ',\n')
                line = []
        if line:
            f.write('  ' + ', '.join(line) + ',\n')
        f.write('};\n')
        f.write('#endif // RESOURCES_EMBED_IMPL\n')

    return 0

if __name__ == '__main__':
    sys.exit(main())
